# Generated by Django 3.2.23 on 2023-12-01 22:22

import apps.categoria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='m_categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='id_categoria', primary_key=True, serialize=False)),
                ('nombre', apps.categoria.models.UpperCharField(max_length=250, null=True, verbose_name='Nombre')),
                ('color', models.CharField(max_length=7, null=True, verbose_name='Color')),
                ('descripcion', models.TextField(max_length=500, null=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categoria', verbose_name='Foto')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creación')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
                'ordering': ['nombre'],
            },
        ),
    ]
